// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.StateMachine;


public class EnemyStateBase : Invert.StateMachine.StateMachine {
    
    private StateMachineTrigger _Tank;
    
    private StateMachineTrigger _Fast;
    
    private StateMachineTrigger _Decoy;
    
    private StateMachineTrigger _Nomal;
    
    public EnemyStateBase(ViewModel vm, string propertyName) : 
            base(vm, propertyName) {
    }
    
    public virtual StateMachineTrigger Tank {
        get {
            if ((this._Tank == null)) {
                this._Tank = new StateMachineTrigger(this, "Tank");
            }
            return this._Tank;
        }
    }
    
    public virtual StateMachineTrigger Fast {
        get {
            if ((this._Fast == null)) {
                this._Fast = new StateMachineTrigger(this, "Fast");
            }
            return this._Fast;
        }
    }
    
    public virtual StateMachineTrigger Decoy {
        get {
            if ((this._Decoy == null)) {
                this._Decoy = new StateMachineTrigger(this, "Decoy");
            }
            return this._Decoy;
        }
    }
    
    public virtual StateMachineTrigger Nomal {
        get {
            if ((this._Nomal == null)) {
                this._Nomal = new StateMachineTrigger(this, "Nomal");
            }
            return this._Nomal;
        }
    }
    
    public override void Compose(List<State> states) {
        base.Compose(states);
    }
}
